#application.yml
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost/health_proba
    username: postgres
    password: postgres

management:
  endpoints:
    web:
      exposure:
        include: health,metrics