#application.yml
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost/health_proba
    username: postgres
    password: postgres
  thymeleaf:
    cache: false

management:
  endpoints:
    web:
      exposure:
        include: health,metrics

springdoc:
  api-docs:
    groups:
      enabled: true
