#application.yml
spring:
  r2dbc:
    url: r2dbc:postgresql://localhost/health_proba
    username: test
    password: test

management:
  endpoints:
    web:
      exposure:
        include: health,metrics

springdoc:
  api-docs:
    groups:
      enabled: true